// INCLUDE THE SLIDING PUZZLE CLASS HEADER
#include "SlidingPuzzle.h"

// MAIN ENTRY POINT OF THE PROGRAM
int main() {
    // CREATE AN INSTANCE OF THE SLIDING PUZZLE GAME
    SlidingPuzzle game;

    // START THE GAME LOOP
    game.play();

    // RETURN SUCCESS CODE TO OPERATING SYSTEM
    // DESTRUCTOR WILL AUTOMATICALLY CLEAN UP MEMORY
    return 0;
}